# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e1e15f9dfe210535267dddd60ff0b9460cf29473e6ca346af76421ad4451de045e7aa026fdf79a6e6deaed2a45c58162fe10cb72508fab996bc3e15a091cfea

test:
  secret_key_base: 863f8cb2f57f29320bc3974291d582b45a19494a1fac39bd67adba6570bcb2fcd58a72341bc150f3e1b61cb5a27f7aa1e4f71e7fdf39863cd9131a4e7656cc06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
